export const ADD_CART = "ADD_CART"
export const DELETE_ITEM = "DELETE_ITEM"
export const INCREASE_ITEM = "INCREASE_ITEM"
export const DECREASE_ITEM = "DECREASE_ITEM"
export const SET_COUNT = "SET_COUNT"
